services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis_db:6379
    networks:
      - app-network
    depends_on:
      - redis_db
  redis_db:
    image: "redis:alpine"
    networks:
      - app-network
    ports:
      - 6379:6379

networks:
  app-network: